# Site settings
title: Portugal
client:
  name: Visit Portugal
  link: https://turismoportugal.solution.weborama.fr/fcgi-bin/dispatch.fcgi?a.A=cl&a.si=5327&a.te=416&a.ra=[RANDOM]&g.lu=
core-se-link: https://www.secretescapes.de/aktuelle-angebote
description: >
  Portugal hat viele Gesichter - Die älteste Nation Europas beeindruckt mit Seefahrer-Erbe, Kulturgütern wie dem Fado und faszinierender Architektur. 

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/portugal" # the subpath of your site, e.g. /blog/
img:     "/portugal/_assets/img"
css:     "/portugal/_assets/css"
js:      "/portugal/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
